Avoid circular import issues.
abhiabhi94/django-flag-app pull request #18
Opened 2021-03-09 00:24 UTC by TSolo315

Django documentation recommends using settings.AUTH_USER_MODEL over get_user_model() when you define a foreign key or many-to-many relation to the user model.

https://docs.djangoproject.com/en/3.1/topics/auth/customizing/

helped fix a circular import issue in my project.

2021-03-09 03:00 UTC, abhiabhi94 requested changes
Thank you for taking the time to contribute.

It would be nice if you could incorporate the changes requested on the specific lines.

In addition, it would be great if you could change the ones mentioned below as well. It will allow consistency throughout the codebase.`

https://github.com/abhiabhi94/django-flag-app/blob/558aaca709e795779d31861fd265ff9a0cd1f87b/flag/api/serializers.py#L7

https://github.com/abhiabhi94/django-flag-app/blob/f26ce46e51bded1d66167f35ad7ab952a961d5a0/tests/base.py#L14

2021-03-09 03:32 UTC, abhiabhi94 requested changes

2021-03-09 03:32 UTC, abhiabhi94 commented on tests/base.py
> +from flag.conf import settings
I'm sorry, this change wasn't required. Since here we need the actual class of the `User` model, we can continue to use `get_user_model()`. Could you please revert this?

2021-03-09 03:34 UTC, abhiabhi94 commented
Also, could you please squash your commits into one? It will help us maintain a clean git history.

2021-03-09 03:45 UTC, abhiabhi94 requested changes

2021-03-09 03:45 UTC, abhiabhi94 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
I think here as well we need the actual class. It is used for comparison below: https://github.com/abhiabhi94/django-flag-app/pull/18/files#diff-98dad9ec1226e864f91d4e9d1237f2a39ecbcdf76978c1d643a6b4b49f8438e3R36

This is the reason why your tests are failing as of now.

2021-03-09 04:36 UTC, TSolo315 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
It's the initializing of the user variable with get_user_model() that is causing me issues. Possible to use get_user_model() for the comparison and AUTH_USER_MODEL otherwise?

2021-03-09 04:48 UTC, abhiabhi94 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
Could you please post your trace back?

2021-03-09 04:57 UTC, TSolo315 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\apps\config.py", line 178, in get_model
    return self.models[model_name.lower()]
KeyError: 'customuser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\contrib\auth\__init__.py", line 157, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\apps\registry.py", line 211, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\apps\config.py", line 180, in get_model
    raise LookupError(
LookupError: App 'users' doesn't have a 'CustomUser' model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\tyler\appdata\local\programs\python\python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\tyler\appdata\local\programs\python\python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "c:\users\tyler\appdata\local\programs\python\python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Website\SHHASMRDBAPI\users\models.py", line 4, in <module>
    from api.models.artist_model import Artist
  File "C:\Website\SHHASMRDBAPI\api\models\__init__.py", line 2, in <module>
    from .video_model import Video
  File "C:\Website\SHHASMRDBAPI\api\models\video_model.py", line 7, in <module>
    from flag.models import Flag
  File "C:\Website\SHHASMRDBAPI\flag\models.py", line 11, in <module>
    from flag.managers import FlagInstanceManager, FlagManager
  File "C:\Website\SHHASMRDBAPI\flag\managers.py", line 6, in <module>
    from flag.utils import get_content_type, get_user_for_model
  File "C:\Website\SHHASMRDBAPI\flag\utils.py", line 12, in <module>
    User = get_user_model()
  File "C:\Users\Tyler\.virtualenvs\SHHASMRDBAPI-MStoyG3z\lib\site-packages\django\contrib\auth\__init__.py", line 161, in get_user_model
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'users.CustomUser' that has not been installed

2021-03-09 05:01 UTC, TSolo315 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
Apparently  get_user_model() only works once Django has imported all models. And my CustomUser model is not loaded when the user = get_user_model() line is run.

2021-03-09 05:54 UTC, abhiabhi94 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
This can happen due to a lot of things. have you listed your `users` app into `INSTALLED_APPS`? if yes, then the reason could be import `get_user_for_model` inside `managers.py`.

2021-03-09 06:14 UTC, TSolo315 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
Yes, the users app is in INSTALLED_APPS. It's been working fine.

I'll see if I can figure it out. It's very possible the problem is something with my setup. I had assumed the change to settings.AUTH_USER_MODEL was a quick 1 to 1 fix -- but obviously hadn't done enough research.

2021-03-09 06:39 UTC, abhiabhi94 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
I have created an issue #19, could you please give a minimal reproducible example there? It will help in resolving the issue faster.

2021-03-09 20:30 UTC, TSolo315 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
My CustomUser  model had a manytomany relationship with a Video model. The video model then had a flag field which would in turn call get_user_model() and lead to either circular import errors or the error listed above depending on the order of the Installed_apps list.

Solution: In CustomUser  instead of importing the video model and initiating the field like:

favorite_videos = models.ManyToManyField(Video, blank=True, related_name='favorite_videos')

Don't import the video model and initialize like:

favorite_videos = models.ManyToManyField('api.Video', blank=True, related_name='favorite_videos')

2021-03-09 20:38 UTC, TSolo315 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
Should the creator field always be null when creating a flag through the api/serializer?

2021-03-10 00:53 UTC, abhiabhi94 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
> Should the creator field always be null when creating a flag through the api/serializer?

No, it should have the logged-in user as the creator.

2021-03-10 02:07 UTC, TSolo315 commented on flag/utils.py
> +User = settings.AUTH_USER_MODEL
Ignore, I figured out the problem. The video model has no field pointing to user as a creator so nothing was matched with get_user_for_model()

2021-03-10 06:11 UTC, abhiabhi94 requested changes

2021-03-10 06:11 UTC, abhiabhi94 commented on flag/utils.py
> +    user = get_user_model()
could you use `User` here in place of `user`?  Small cases are generally used for objects while here we are actually obtaining a `class`.

2021-03-10 06:29 UTC, abhiabhi94 commented
could you please squash your commits into one? it will help us in maintaining a clean git history.

2021-03-10 07:23 UTC, abhiabhi94 commented
can you update your branch with the latest changes from the `main` branch? I have updated the continuous integration process.

2021-03-10 10:10 UTC, merged